### PR TITLE
Fix compatibility in Windows (CI/CD and locally)

### LINKED ISSUE #45: Run tests in different OS
Run the tests on different OS:

- [x] Linux (Ubuntu)
- [ ] Windows
- [x] Mac

### LINKED ISSUE #81: Enable working on Windows
Failing  tests: https://github.com/Appsilon/shiny.benchmark/actions/runs/3361979812/jobs/5573090092
PR comments: https://github.com/Appsilon/shiny.benchmark/pull/79#issuecomment-1297315636

### PR DESCRIPTION
**Pull request by averissimo**
### Link to the Issue

Closes  #81
Closes #45

### Definition of Done

User is able to use shiny.benchmark for cypress/shinytest tests in Windows

### How to test changes

* Setup a windows environment and create an app with cypress/shinytest2 tests
* Check if CI/CD test passes in windows environment

### Tasks for PR author

- [x] Test your change and ensure there is no regression
- [x] Change has a corresponding issue. ***Ensure it is linked in GitHub***
- [x] Author of the change opened a pull request and assigned a reviewer

### General policy:

- If applicable - add instructions for testing
- If there’s no issue, create it. Each issue needs to be well defined and described.
- All interaction with a user, user-facing messages, plots, reports etc. are written from the perspective of the person using or receiving it. They are understandable and helpful to this person. If a user sees an error message, there is a call to action, i.e. the user knows what to do to fix it.
- README, other documentation and code comments that we have is updated with all information related to the change.
- All code has been peer-reviewed before merging into any main branch
- All changes have been merged into the main branch we use for development.
- Continuous integration checks (linter, unit tests, integration tests) are configured and pass.
- Optional: unit tests added for all new or changed logic.
- All task requirements satisfied. If not describe it here. The reviewer is responsible to verify each aspect of the task.
- Change covers only things in task. Please create new PR if you want to fix something else.

### CODE REVIEW

File: R/benchmark_shinytest2.R [hunk 1]
```diff
@@ -62,7 +63,7 @@ benchmark_shinytest2 <- function(
         restore_env(branch = current_branch, renv_prompt = renv_prompt)
 
       # Cleaning the temporary directory
-      unlink(x = file.path(project_path, "tests"), recursive = TRUE)
+      unlink(fs::path(project_path, "tests"))
```
Comment (DouglasMesquita) [inline R/benchmark_shinytest2.R:66]: fs::file_delete maybe? to keep the pattern

File: R/utils.R [hunk 2]
```diff
@@ -81,6 +81,45 @@ checkout <- function(branch, debug) {
...
 }
 
+#' @title Running the node script "performance_test" is system-dependent
+#'
+#' @param project_path path to project directory (one level above node)
+#'
+#' @keywords internal
+performance_test_cmd <- function(project_path) {
+  if (grepl("win", .Platform$OS.type, ignore.case = TRUE)) {
+    glue("yarn --cwd \"{fs::path(project_path, 'node')}\" performance-test")
```
Comment (DouglasMesquita) [inline R/utils.R:91]: Maybe it also works on linux. Did you try? Then we do not need the if here.

File: R/utils.R [hunk 3]
```diff
@@ -169,11 +208,12 @@ summarise_commit <- function(object) {
 #' the selected `path`.
 #'
 #' @param path A character vector of full path name
+#' @param force Create example even if directory is not empty
```
Comment (DouglasMesquita) [inline R/utils.R:211]: Great

File: R/utils_cypress.R [hunk 4]
```diff
@@ -12,28 +12,43 @@ create_cypress_structure <- function(app_dir, port, debug) {
...
   # create a path root linked to the main directory app
-  file.symlink(from = app_dir, to = root_path)
+  tryCatch(
+    expr = {
+      fs::link_create(app_dir, root_path, symbolic = TRUE)
+    },
+    error = function(e) {
+      # If system cannot symlink then try to clone the repository
+      #  This may happen on some windows versions
+      #  This can be an expensive operation on big repositories
```
Comment (DouglasMesquita) [inline R/utils_cypress.R:39]: What do you think about adding a prompt question if the user really wants to perform it (since it is a big operation)?

File: R/utils_cypress.R [hunk 5]
```diff
@@ -68,7 +83,10 @@ create_node_list <- function(tests_path, port) {
       "performance-test" = glue(
         "start-server-and-test run-app http://localhost:{port} run-cypress"
       ),
-      "run-app" = glue("cd root && Rscript -e 'shiny::runApp(port = {port})'"),
+      "run-app" = glue(
+        "cd root && ",
```
Comment (DouglasMesquita) [inline R/utils_cypress.R:87]: I think the && is not needed in this case (I am not sure)

File: R/globals.R [hunk 6]
```diff
@@ -12,3 +12,6 @@ utils::globalVariables(
     "total_time"
   )
 )
+
+# Setting threshold to debug (temporary and should be removed)
+logger::log_threshold(logger::INFO)
```
Comment (DouglasMesquita) [inline R/globals.R:17]: Is it important in this version?

**Review by DouglasMesquita — CHANGES_REQUESTED** [review]
It is an awesome job. I like the migration to sf and also I am super happy it is now working on windows.

I have some comments but most of them are just comments. One thing I think is important here is to add a question for the user in case of cloning the repo. Maybe the user will abort operation.

File: R/globals.R (hunk 6 above)
Comment (averissimo) [reply R/globals.R:17]: Not really, I'll remove it. I see that there's a different task with this purpuse

File: R/utils_cypress.R (hunk 5 above)
Comment (averissimo) [reply R/utils_cypress.R:87]: The change here was using " instead of ' inside the string. Windows on my machine had a problem with this.

@DouglasMesquita do you suggest using ";" instead ? "&&" 

ps. I find it funny that windows doesn't have a problem with "cd" when calling node (the original exception with R code)

File: R/utils_cypress.R (hunk 4 above)
Comment (averissimo) [reply R/utils_cypress.R:39]: Will do!

Do you want to debate if it's even necessary. Reaching this exception will be very rare now that we're using the `fs` package

File: R/utils.R (hunk 2 above)
Comment (averissimo) [reply R/utils.R:91]: Initially I had a problem with the different command, hence the platform-dependant. I'll check it again now that it has stabilized.

File: R/benchmark_shinytest2.R (hunk 1 above)
Comment (averissimo) [reply R/benchmark_shinytest2.R:66]: I think this one will have to stick. When using `fs::file_delete` it creates a problem with CI/CD as it cannot delete a file that is being used (EBUSY) error.

I couldn't figure out what process was using it and had to revert to `unlink`. I'll check one more time and place a comment indicating why it doesn't use `fs`

File: R/utils.R (hunk 2 above)
Comment (averissimo) [reply R/utils.R]: I tried it and it fails on windows! I think it needs to be "&&"

File: R/utils_cypress.R (hunk 5 above)
Comment (averissimo) [reply R/utils_cypress.R:99]: I tried it and it fails on windows! I think it needs to be "&&", unless you have another suggestion

**Review by DouglasMesquita — APPROVED** [review]
Great job! I love the menu with the option :)
